version: '3.8'

services:
  thirdshop-landing:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: thirdshop-landing
    ports:
      - "3211:4321"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
      - PORT=4321



